services:
  - type: web
    name: fiyattakip-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    nodeVersion: 20.18.0
    envVars:
      - key: NODE_ENV
        value: production
